import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/interactions.ts",
    "src/element-queries.ts",
    "src/navigation.ts",
    "src/advanced-interactions.ts",
    "src/screenshots.ts",
    "src/assertions.ts",
    "src/waiting.ts",
    "src/retry.ts",
    "src/test-utils.ts",
    "src/accessibility.ts",
    "src/storage.ts",
    "src/network.ts",
    "src/network-monitoring.ts",
    "src/dialogs.ts",
    "src/tables.ts",
    "src/page-objects.ts",
    "src/test-data.ts",
    "src/types.ts",
    "src/error-handling.ts",
    "src/performance.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  minify: true,
  sourcemap: true,
  treeshake: true,
  splitting: false,
  target: "es2020",
  outDir: "dist",
  onSuccess: "npm run build:types",
});
